In [1]:
import numpy as np




In [ ]:
def parametros(epocas,pobacion,pc,pm,presicion,m):
    indices=np.array([[3,8,2],[1,-2,4],[-5,3,-11]])
    individuos=np.random.randn(pobacion,3)*10
    

In [9]:
individuos=np.random.randn(1000,3)
Matriz=np.array([[3,8,2],[1,-2,4],[-5,3,11]])
total=np.array([25,12,4])
epocas=1000
i=0
s=0
while i < epocas:
    i=i+1
    
    ptemp=[]
    fitness=fitnesst(individuos,Matriz,total)

    indices=np.argsort(fitness)
    ordenado=individuos[indices]
    sas=cruce_mut(ordenado)
    individuos=np.array(sas)
    s=s+1
    if s==100:
        s=0
        valores=np.expand_dims(fitness,axis=1)
        muestra=np.concatenate((individuos,valores[indices]),axis=1) 
        print(muestra)
    if i ==epocas:
        eval=np.dot(Matriz,individuos[0])
        print(eval)
    


[[ 2.40587852  1.9880354   0.91560788  9.96102651]
 [ 2.40587852  1.9880354   0.91560788  9.96102651]
 [ 2.40587852  1.9880354   0.91560788  9.96102651]
 ...
 [ 2.40587852  2.16497055  0.91560788 15.29463215]
 [ 2.16529067  1.9880354   0.91560788 15.29463215]
 [ 1.9487616   1.9880354   0.91560788 15.29463215]]
[[ 2.40587852  1.78923186  0.91560788  9.96102651]
 [ 2.40587852  1.78923186  0.91560788  9.96102651]
 [ 2.16529067  1.9880354   0.91560788  9.96102651]
 ...
 [ 2.40587852  2.18683894  0.91560788 15.29463215]
 [ 2.40587852  2.18683894  0.91560788 15.29463215]
 [ 2.40587852  2.18683894  0.91560788 15.42891554]]
[[ 2.40587852  2.18683894  0.91560788  9.96102651]
 [ 2.40587852  2.18683894  0.91560788  9.96102651]
 [ 2.40587852  1.78923186  0.91560788  9.96102651]
 ...
 [ 2.40587852  1.9880354   0.91560788 15.29463215]
 [ 2.40587852  1.9880354   0.91560788 15.29463215]
 [ 2.40587852  1.9880354   0.91560788 15.82896422]]
[[ 2.64646637  1.9880354   0.91560788  9.96102651]
 [ 2.64646637

In [8]:

def fitnesst(individuos,Matriz,total):
    fitness=[]
    for i in individuos:
        eval=abs((np.dot(Matriz,i))-total).sum()
        fitness.append(eval)
    fitness=np.array(fitness)    
    return fitness

def cruce_mut(genotipos):
    pobtemp=[]
    for i in range(0,len(genotipos),2):
        if len(pobtemp) == 0:
            padre1=genotipos[0]
            padre2=genotipos[1]
        else:
            elemento1=np.random.randint(0,len(genotipos))
            elemento2=np.random.randint(0,len(genotipos))
            padre1=genotipos[elemento1]
            padre1=genotipos[elemento2]
        
            
        tasacruce=np.random.randint(0,100)
        if tasacruce <90:
            gen=np.random.randint(0,2)
            hijo1 = np.concatenate((padre1[:gen], padre2[gen:]))
            hijo2 = np.concatenate((padre2[:gen], padre1[gen:]))
            tasamut=np.random.randint(0,1000)
            if tasamut>850:
                hijo1[gen]=hijo1[gen]*1.10
                hijo2[gen]=hijo2[gen]*1.10
            elif tasamut<150:
                hijo1[gen]=hijo1[gen]*0.90
                hijo2[gen]=hijo2[gen]*0.90
            else:
                0
        else:
            hijo1=padre1
            hijo2=padre2
        pobtemp.append(hijo1)
        pobtemp.append(hijo2)
    return pobtemp
        


In [15]:
padre1=ordenado[0]
padre2=ordenado[1]

hijo1 = padre1[:2] + padre1[2:]
hijo2 = padre2[:2] + padre2[2:]

In [17]:
padre2[2:]

array([-5.07864002])