# Fundamentos de Python con Numpy

Bienvenido a su primera tarea. Este ejercicio le ofrece una breve introducción a Python. Incluso si has usado Python antes, esto te ayudará a familiarizarte con las funciones que necesitaremos.  

**Instrucciones
- Utilizarás Python 3.
- Evite usar bucles for y while, a menos que se le indique explícitamente que lo haga.
- Después de codificar tu función, ejecuta la celda que está justo debajo de ella para comprobar si tu resultado es correcto.

**Después de esta tarea usted:**
- Serás capaz de utilizar iPython Notebooks
- Serás capaz de utilizar las funciones de numpy y las operaciones matriciales/vectoriales de numpy
- Entender el concepto de "transmisión"
- Serás capaz de vectorizar código

¡Empecemos!

## Nota importante sobre el envío

Antes de enviar tu tarea, por favor asegúrate de que no estás haciendo lo siguiente

1. No ha añadido ninguna declaración _extra_ `print` en la tarea.
2. No ha añadido ninguna celda de código _extra_ en la tarea.
3. No ha cambiado ningún parámetro de la función.
4. No ha utilizado ninguna variable global dentro de sus ejercicios calificados. A menos que se le indique específicamente que lo haga, por favor absténgase de hacerlo y utilice las variables locales en su lugar.
5. No está cambiando el código de asignación donde no es necesario, como la creación de variables _extra_.



## Índice de contenidos
- [Acerca de iPython Notebooks](#0)
    - [Ejercicio 1](#ex-1)
- [1 - Construir funciones básicas con numpy](#1)
    - [1.1 - función sigmoidea, np.exp()](#1-1)
        - [Ejercicio 2 - basic_sigmoid](#ex-2)
        - [Ejercicio 2 - basic_sigmoid](#ex-3)
    - [1.2 - Gradiente sigmoide](#1-2)
        - [Ejercicio 4 - sigmoid_derivative](#ex-4)
    - [1.3 - Reshaping arrays](#1-3)
        - [Ejercicio 5 - image2vector](#ex-5)
    - [1.4 - Normalización de filas](#1-4)
        - [Ejercicio 6 - normalizar_filas](#ex-6)
        - [Ejercicio 7 - softmax](#ex-7)
- [2 - Vectorización](#2)
    - [2.1 Implement the L1 and L2 loss functions](#2-1)
        - [Ejercicio 8 - L1](#ex-8)
        - [Ejercicio 9 - L2](#ex-9)

<a name='0'></a>
## Acerca de iPython Notebooks ##

Los cuadernos iPython son entornos de codificación interactivos incrustados en una página web. En esta clase utilizarás cuadernos iPython. Sólo tienes que escribir el código entre el comentario # your code here. Después de escribir tu código, puedes ejecutar la celda presionando "SHIFT "+"ENTER" o haciendo clic en "Ejecutar Celda" (denotado por un símbolo de play) en la barra superior del cuaderno. 

A menudo especificaremos "(≈ X líneas de código)" en los comentarios para indicarle la cantidad de código que debe escribir. Es sólo una estimación aproximada, así que no te sientas mal si tu código es más largo o más corto.

<a name='ex-1'></a>
### Ejercicio 1
Establezca el test `"Hola Mundo"` en la celda de abajo para imprimir "Hola Mundo" y ejecute las dos celdas de abajo.

In [1]:
# (≈ 1 line of code)
#test = 
# YOUR CODE STARTS HERE
test='Hola Mundo'

# YOUR CODE ENDS HERE

In [2]:
print ("test: " + test)

test: Hola Mundo


**Salida esperada**:
test: Hola Mundo

<font color='blue'>
<b>Lo que hay que recordar</b>:
    
- Ejecuta tus celdas usando SHIFT+ENTER (o "Run cell")
- Escribe el código en las áreas designadas usando sólo Python 3
- No modifiques el código fuera de las áreas designadas

<a name='1'></a>
## 1 - Construcción de funciones básicas con numpy ##

Numpy es el principal paquete para la computación científica en Python. Está mantenido por una gran comunidad (www.numpy.org). En este ejercicio aprenderás varias funciones clave de numpy como `np.exp`, `np.log` y `np.reshape`. Necesitarás saber cómo usar estas funciones para futuras tareas.

<a name='1-1'></a>
### 1.1 - función sigmoide, np.exp() ###

Antes de usar `np.exp()`, usarás `math.exp()` para implementar la función sigmoide. Entonces verás por qué `np.exp()` es preferible a `math.exp()`.

<a name='ex-2'></a>
### Ejercicio 2 - sigmoide básico
Construye una función que devuelva el sigmoide de un número real x. Usa `math.exp(x)` para la función exponencial.

**Recordatorio**:
$sigmoide(x) = \frac{1}{1+e^{-x}}$ a veces también se conoce como función logística. Es una función no lineal utilizada no sólo en el Aprendizaje Automático (Regresión Logística), sino también en el Aprendizaje Profundo.

<img src="images/Sigmoid.png" style="width:500px;height:228px;">

Para referirse a una función perteneciente a un paquete específico se puede llamar utilizando `nombre_del_paquete.función()`. Ejecute el siguiente código para ver un ejemplo con `math.exp()`.

In [3]:
import math
from public_tests import *

# GRADED FUNCTION: basic_sigmoid

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    # (≈ 1 line of code)
    # s = 
    # YOUR CODE STARTS HERE
    
    s=1/(1+math.exp(-x))
    # YOUR CODE ENDS HERE
    
    return s

In [4]:
print("basic_sigmoid(1) = " + str(basic_sigmoid(1)))

basic_sigmoid_test(basic_sigmoid)

basic_sigmoid(1) = 0.7310585786300049
 All tests passed.


En realidad, rara vez utilizamos la biblioteca "math" en el aprendizaje profundo porque las entradas de las funciones son números reales. En el aprendizaje profundo utilizamos principalmente matrices y vectores. Por eso numpy es más útil. 

In [5]:
### Una razón por la que usamos "numpy" en lugar de "math" en Deep Learning ###

x = [1, 2, 3] # x se convierte en un objeto de lista python
basic_sigmoid(x) # verás que esto da un error cuando lo ejecutes, porque x es un vector.

TypeError: bad operand type for unary -: 'list'

De hecho, si $ x = (x_1, x_2, ..., x_n)$ es un vector de filas entonces `np.exp(x)` aplicará la función exponencial a cada elemento de x. La salida será entonces: `np.exp(x) = (e^{x_1}, e^{x_2}, ..., e^{x_n})`.

In [6]:
import numpy as np

# example of np.exp
t_x = np.array([1, 2, 3])
print(np.exp(t_x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


Además, si x es un vector, entonces una operación de Python como $s = x + 3$ o $s = \frac{1}{x}$ dará como resultado como un vector del mismo tamaño que x.

In [7]:
# example of vector operation
t_x = np.array([1, 2, 3])
print (t_x + 3)

[4 5 6]


Siempre que necesites más información sobre una función de numpy, te animamos a que consultes [la documentación oficial](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.exp.html). 

También puedes crear una nueva celda en el cuaderno y escribir `np.exp?` (por ejemplo) para acceder rápidamente a la documentación.

<a name='ex-3'></a>
### Ejercicio 3 - sigmoide
Implementa la función sigmoide usando numpy. 

**Instrucciones: x puede ser un número real, un vector o una matriz. Las estructuras de datos que usamos en numpy para representar estas formas (vectores, matrices...) se llaman arrays de numpy. No necesitas saber más por ahora.
$$ \text{For } x \in \mathbb{R}^n \text{,     } sigmoid(x) = sigmoid\begin{pmatrix}
    x_1  \\
    x_2  \\
    ...  \\
    x_n  \\
\end{pmatrix} = \begin{pmatrix}
    \frac{1}{1+e^{-x_1}}  \\
    \frac{1}{1+e^{-x_2}}  \\
    ...  \\
    \frac{1}{1+e^{-x_n}}  \\
\end{pmatrix}\tag{1} $$

In [8]:
# GRADED FUNCTION: sigmoid

def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    
    # (≈ 1 line of code)
    # s = 
    # YOUR CODE STARTS HERE
    
    s=s=1/(1+np.exp(-x))
    # YOUR CODE ENDS HERE
    
    return s

In [9]:
t_x = np.array([1, 2, 3])
print("sigmoid(t_x) = " + str(sigmoid(t_x)))

sigmoid_test(sigmoid)

sigmoid(t_x) = [0.73105858 0.88079708 0.95257413]
 All tests passed.


<a name='1-2'></a>
### 1.2 - Gradiente Sigmoide

Como has visto en la clase, necesitarás calcular gradientes para optimizar las funciones de pérdida utilizando la retropropagación. Vamos a codificar tu primera función de gradiente.

<a name='ex-4'></a>
### Ejercicio 4 - sigmoid_derivative
Implementa la función sigmoid_grad() para calcular el gradiente de la función sigmoide con respecto a su entrada x. La fórmula es 

$$sigmoid_derivative(x) = \sigma'(x) = \sigma(x) (1 - \sigma(x))\tag{2}$$

A menudo se codifica esta función en dos pasos:
1. Set s to be the sigmoid of x. You might find your sigmoid(x) function useful.
2. Compute $\sigma'(x) = s(1-s)$

In [10]:
# GRADED FUNCTION: sigmoid_derivative

def sigmoid_derivative(x):
    """
    Calcula el gradiente (también llamado pendiente o derivada) de la función sigmoidea con respecto a su entrada x.
    Puedes almacenar la salida de la función sigmoide en variables y luego usarla para calcular el gradiente.
    
  Argumentos:
    x -- Un escalar o un array numpy

    Retorno:
    ds -- El gradiente calculado.
    """
    
    #(≈ 2 lines of code)
    # s = 
    # ds = 
    # YOUR CODE STARTS HERE
    s=s=1/(1+np.exp(-x))
    ds=s*(1-s)
    
    # YOUR CODE ENDS HERE
    
    return ds

In [11]:
t_x = np.array([1, 2, 3])
print ("sigmoid_derivative(t_x) = " + str(sigmoid_derivative(t_x)))

sigmoid_derivative_test(sigmoid_derivative)

sigmoid_derivative(t_x) = [0.19661193 0.10499359 0.04517666]
 All tests passed.


<a name='1-3'></a>
### 1.3 - Reshaping  de arrays ###

Dos funciones numpy comunes utilizadas en el aprendizaje profundo son [np.shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) y [np.reshape()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html). 
- X.shape se utiliza para obtener la forma (dimensión) de una matriz/vector X. 
- X.reshape(...) se utiliza para cambiar la forma de X a otra dimensión. 

Por ejemplo, en informática, una imagen se representa por una matriz 3D de forma $(longitud, altura, profundidad = 3)$. Sin embargo, cuando se lee una imagen como entrada de un algoritmo se convierte en un vector de forma $(longitud*altura*3, 1)$. En otras palabras, se "desenrolla", o se da nueva forma, a la matriz 3D en un vector 1D.

<img src="images/image2vector_kiank.png" style="width:500px;height:300;">

<a name='ex-5'></a>
### imagen2vector
Implementa `image2vector()` que toma una entrada de forma (longitud, altura, 3) y devuelve un vector de forma (longitud*altura*3, 1). Por ejemplo, si quieres transformar un array v de forma (a, b, c) en un vector de forma (a*b,c) debes hacer:
``` python
v = v.reshape((v.shape[0] * v.shape[1], v.shape[2])) # v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c
```
- Por favor, no codifiques las dimensiones de la imagen como una constante. En su lugar, busca las cantidades que necesitas con `image.shape[0]`, etc. 
- Puedes usar v = v.reshape(-1, 1). Sólo asegúrate de entender por qué funciona.

In [12]:
# GRADED FUNCTION:image2vector

def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    
    # (≈ 1 line of code)
    # v =
    # YOUR CODE STARTS HERE
    v=image.reshape((image.shape[0]*image.shape[1]*image.shape[2],1))
    
    # YOUR CODE ENDS HERE
    
    return v


In [13]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
t_image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])



print ("image2vector(image) = " + str(image2vector(t_image)))

image2vector_test(image2vector)


image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]
 All tests passed.


<a name='1-4'></a>
### 1.4 - Normalización de filas

Otra técnica común que utilizamos en Machine Learning y Deep Learning es normalizar nuestros datos. A menudo conduce a un mejor rendimiento porque el descenso de gradiente converge más rápido después de la normalización. Aquí, por normalización nos referimos a cambiar x a $ \frac{x}{| x\|} $ (dividiendo cada vector de fila de x por su norma).

Por ejemplo, si 
$$x = \begin{bmatrix}
        0 & 3 & 4 \\
        2 & 6 & 4 \\
\end{bmatrix}\tag{3}$$ 
enotonces
$$\| x\| = \text{np.linalg.norm(x, axis=1, keepdims=True)} = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{4} $$
y
$$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{5}$$ 

Tenga en cuenta que puede dividir matrices de diferentes tamaños y funciona bien: esto se llama emisión y lo aprenderá en la parte 5.

Con `keepdims=True` el resultado se emitirá correctamente contra la x original.

El eje = 1 significa que vas a obtener la norma en una fila. Si necesitas la norma en forma de columna, necesitarás poner `axis=0`. 

numpy.linalg.norm tiene otro parámetro `ord` en el que se especifica el tipo de normalización que se va a realizar (en el ejercicio de abajo se hará 2-norm). Para familiarizarte con los tipos de normalización puedes visitar [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)

<a name='ex-6'></a>
### Ejercicio 6 - normalizar_filas
Implementar normalizeRows() para normalizar las filas de una matriz. Después de aplicar esta función a una matriz de entrada x, cada fila de x debe ser un vector de longitud unitaria (es decir, de longitud 1).

**Nota: No intentes usar `x /= x_norm`. Para la división de matrices, numpy debe emitir la norma x, la cual no es soportada por el operante `/=`.

In [14]:
# GRADED FUNCTION: normalize_rows

def normalize_rows(x):
    """
    Implementa una función que normaliza cada fila de la matriz x (para que tenga longitud unitaria).
    
    Argumento:
    x -- Una matriz numpy de forma (n, m)
    
    Devuelve:
    x -- La matriz numpy normalizada (por fila). Se permite modificar x.
    """
    
    #(≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    # x_norm =
    # Divide x by its norm.
    # x =
    # YOUR CODE STARTS HERE
    x_norm=np.linalg.norm(x,ord=2,axis=1,keepdims=True)
    x=x/x_norm
    # YOUR CODE ENDS HERE

    return x

In [15]:
x = np.array([[0, 3, 4],
              [1, 6, 4]])
print("normalizeRows(x) = " + str(normalize_rows(x)))

normalizeRows_test(normalize_rows)

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]
 All tests passed.


**Nota**:
En normalize_rows(), puedes intentar imprimir las formas de x_norm y x, y luego volver a ejecutar la evaluación. Descubrirá que tienen formas diferentes. Esto es normal dado que x_norm toma la norma de cada fila de x. Así que x_norm tiene el mismo número de filas pero sólo 1 columna. Entonces, ¿cómo funcionó al dividir x por x_norm? Esto se llama difusión y ¡ahora hablaremos de ello! 

<a name='ex-7'></a>
### Ejercicio 7 - softmax
Implementa una función softmax usando numpy. Puedes pensar en softmax como una función de normalización utilizada cuando tu algoritmo necesita clasificar dos o más clases. Aprenderás más sobre softmax en el segundo curso de esta especialización.

**Instrucciones:
- $\text{for } x \in \mathbb{R}^{1\times n} \text{,     }$

\begin{align*}
 softmax(x) &= softmax\left(\begin{bmatrix}
    x_1  &&
    x_2 &&
    ...  &&
    x_n  
\end{bmatrix}\right) \\&= \begin{bmatrix}
    \frac{e^{x_1}}{\sum_{j}e^{x_j}}  &&
    \frac{e^{x_2}}{\sum_{j}e^{x_j}}  &&
    ...  &&
    \frac{e^{x_n}}{\sum_{j}e^{x_j}} 
\end{bmatrix} 
\end{align*}

- $\text{for a matrix } x \in \mathbb{R}^{m \times n} \text{,  $x_{ij}$ se asigna al elemento en el $i^{th}$ fila y $j^{th}$ columna de  $x$, por lo que tenemos: }$  

\begin{align*}
softmax(x) &= softmax\begin{bmatrix}
            x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
            x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
            \vdots & \vdots & \vdots & \ddots & \vdots \\
            x_{m1} & x_{m2} & x_{m3} & \dots  & x_{mn}
            \end{bmatrix} \\ \\&= 
 \begin{bmatrix}
    \frac{e^{x_{11}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{12}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{13}}}{\sum_{j}e^{x_{1j}}} & \dots  & \frac{e^{x_{1n}}}{\sum_{j}e^{x_{1j}}} \\
    \frac{e^{x_{21}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{22}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{23}}}{\sum_{j}e^{x_{2j}}} & \dots  & \frac{e^{x_{2n}}}{\sum_{j}e^{x_{2j}}} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \frac{e^{x_{m1}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m2}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m3}}}{\sum_{j}e^{x_{mj}}} & \dots  & \frac{e^{x_{mn}}}{\sum_{j}e^{x_{mj}}}
\end{bmatrix} \\ \\ &= \begin{pmatrix}
    softmax\text{(first row of x)}  \\
    softmax\text{(second row of x)} \\
    \vdots  \\
    softmax\text{(last row of x)} \\
\end{pmatrix} 
\end{align*}

**Notes:**
Note that later in the course, you'll see "m" used to represent the "number of training examples", and each training example is in its own column of the matrix. Also, each feature will be in its own row (each row has data for the same feature).  
Softmax should be performed for all features of each training example, so softmax would be performed on the columns (once we switch to that representation later in this course).

However, in this coding practice, we're just focusing on getting familiar with Python, so we're using the common math notation $m \times n$  
where $m$ is the number of rows and $n$ is the number of columns.

In [16]:
# GRADED FUNCTION: softmax

def softmax(x):
    """Calcula el softmax para cada fila de la entrada x.

    Su código debe funcionar para un vector de filas y también para matrices de forma (m,n).

    Argumento:
    x -- Una matriz numpy de forma (m,n)

    Devuelve:
    s -- Una matriz numpy igual al softmax de x, de forma (m,n)
    """
    
    #(≈ 3 líneas de código)
    # Aplica exp() de forma elemental a x. Usa np.exp(...).
    # x_exp = ...

    # Crear un vector x_sum que sume cada fila de x_exp. Usa np.sum(..., axis = 1, keepdims = True).
    # x_sum = ...
    
    # Calcula softmax(x) dividiendo x_exp por x_sum. Debería utilizar automáticamente la emisión de numpy.
    # s = ...
    
    # YOUR CODE STARTS HERE
    x_exp=np.exp(x)
    x_sum=np.sum(x_exp,axis=1,keepdims=True)
    s=x_exp/x_sum
    # YOUR CODE ENDS HERE
    
    return s

In [17]:
t_x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(t_x)))

softmax_test(softmax)

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]
 All tests passed.


#### Notas
- Si imprimes las formas de x_exp, x_sum y s arriba y vuelves a ejecutar la celda de evaluación, verás que x_sum es de forma (2,1) mientras que x_exp y s son de forma (2,5). **x_exp/x_sum** funciona gracias a la transmisión de python.

¡Felicitaciones! Ahora tienes una comprensión bastante buena de numpy python y has implementado algunas funciones útiles que vas a utilizar en el aprendizaje profundo.

<font color='blue'>
<b>Lo que hay que recordar:</b>
    
- np.exp(x) funciona para cualquier np.array x y aplica la función exponencial a cada coordenada
- la función sigmoidea y su gradiente
- image2vector se utiliza comúnmente en el aprendizaje profundo
- np.reshape es ampliamente utilizado. En el futuro, verás que mantener las dimensiones de tus matrices/vectores en orden te ayudará a eliminar muchos errores. 
- numpy tiene funciones incorporadas eficientes
- la transmisión es extremadamente útil

<a name='2'></a>
## 2 - Vectorización


En el aprendizaje profundo, se trabaja con conjuntos de datos muy grandes. Por lo tanto, una función no óptima desde el punto de vista computacional puede convertirse en un enorme cuello de botella en su algoritmo y puede dar lugar a un modelo que tarda siglos en ejecutarse. Para asegurarse de que su código es computacionalmente eficiente, utilizará la vectorización. Por ejemplo, intente diferenciar entre las siguientes implementaciones del producto punto/extremo/elemento.

In [18]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### APLICACIÓN CLÁSICA DEL PRODUCTO PUNTO DE LOS VECTORES ###
tic = time.process_time()
dot = 0

for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### APLICACIÓN CLÁSICA DEL PRODUCTO EXTERIOR ###
tic = time.process_time()
outer = np.zeros((len(x1), len(x2))) # creamos una matriz len(x1)*len(x2) con sólo ceros

for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i] * x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Tiempo de cálculo = " + str(1000 * (toc - tic)) + "ms")

### APLICACIÓN CLÁSICA DE LOS ELEMENTOS ###
tic = time.process_time()
mul = np.zeros(len(x1))

for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Tiempo de cálculo = " + str(1000 * (toc - tic)) + "ms")

### IMPLEMENTACIÓN CLÁSICA DEL PRODUCTO PUNTO GENERAL  ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])

for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Tiempo de cálculo = " + str(1000 * (toc - tic)) + "ms")

dot = 278
 ----- Computation time = 15.625ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
 

In [19]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### PRODUCTO PUNTO VECTORIAL DE VECTORES ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Tiempo de cálculo = " + str(1000 * (toc - tic)) + "ms")

### PRODUCTO EXTERIOR VECTORIZADO ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Tiempo de cálculo = " + str(1000 * (toc - tic)) + "ms")

### MULTIPLICACIÓN VECTORIAL POR ELEMENTOS ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Tiempo de cálculo = " + str(1000*(toc - tic)) + "ms")

### PRODUCTO PUNTO GENERAL VECTORIZADO ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Tiempo de cálculo = " + str(1000 * (toc - tic)) + "ms")

dot = 278
 ----- Tiempo de cálculo = 0.0ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Tiempo de cálculo = 0.0ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Tiempo de cálculo = 0.0ms
gdot = [16.17135356 24.10461648 17.06207669]
 ----- Tiempo de cálculo = 0.0ms


Como habrá notado, la implementación vectorizada es mucho más limpia y eficiente. Para vectores/matrices más grandes, las diferencias en el tiempo de ejecución son aún mayores. 

**Nota** que `np.dot()` realiza una multiplicación matriz-matriz o matriz-vector. Esto es diferente de `np.multiply()` y del operador `*` (que es equivalente a `.*` en Matlab/Octave), que realiza una multiplicación elemento a elemento.

<a name='2-1'></a>
### 2.1 Implementar las funciones de pérdida L1 y L2

<a name='ex-8'></a>
### Ejercicio 8 - L1 
Implementa la versión vectorizada en numpy de la pérdida L1. Puedes encontrar útil la función abs(x) (valor absoluto de x).

**Recordatorio**:
- La pérdida se utiliza para evaluar el rendimiento de tu modelo. Cuanto mayor sea la pérdida, más diferentes serán tus predicciones ($ \hat{y} $) de los valores reales ($y$). En el aprendizaje profundo, se utilizan algoritmos de optimización como el Gradient Descent para entrenar su modelo y minimizar el coste.
- La pérdida L1 se define como:
$$\begin{align*} & L_1(\hat{y}, y) = \sum_{i=0}^{m-1}|y^{(i)} - \hat{y}^{(i)}| \end{align*}\tag{6}$$

In [20]:
# GRADED FUNCTION: L1

def L1(yhat, y):
    """
    Argumentos:
    yhat -- vector de tamaño m (etiquetas predichas)
    y -- vector de tamaño m (etiquetas verdaderas)
    
    Devuelve:
    loss -- el valor de la función de pérdida L1 definida anteriormente
    """
    
    #(≈ 1 line of code)
    # loss = 
    # YOUR CODE STARTS HERE
    loss = np.sum(abs(y - yhat))
    
    # YOUR CODE ENDS HERE
    
    return loss

In [21]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat, y)))

L1_test(L1)

L1 = 1.1
 All tests passed.


<a name='ex-9'></a>
### Exercise 9 - L2
Implementa la versión vectorizada de numpy de la pérdida L2. Hay varias formas de implementar la pérdida L2, pero puedes encontrar útil la función np.dot(). Como recordatorio, si $x = [x_1, x_2, ..., x_n]$, entonces `np.dot(x,x)` = $\sum_{j=0}^n x_j^{2}$. 

- La pérdida L2 se define como $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^{m-1}(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [22]:
# GRADED FUNCTION: L2

def L2(yhat, y):
    """
    Argumentos:
    yhat -- vector de tamaño m (etiquetas predichas)
    y -- vector de tamaño m (etiquetas verdaderas)
    
    Devuelve:
    loss -- el valor de la función de pérdida L2 definida anteriormente
    """
    
    #(≈ 1 line of code)
    # loss = ...
    # YOUR CODE STARTS HERE
    
    loss = np.sum(np.square(y - yhat))
    # YOUR CODE ENDS HERE
    
    return loss

In [23]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

print("L2 = " + str(L2(yhat, y)))

L2_test(L2)

L2 = 0.43
 All tests passed.


Felicitaciones por haber completado esta tarea. Esperamos que este pequeño ejercicio de calentamiento te ayude en las futuras tareas, que serán más emocionantes e interesantes.

<font color='blue'>
<b>Lo que hay que recordar:</b>
    
- La vectorización es muy importante en el aprendizaje profundo. Proporciona eficiencia computacional y claridad.
- Has revisado la pérdida L1 y L2.
- Estás familiarizado con muchas funciones de numpy como np.sum, np.dot, np.multiply, np.maximum, etc...